# Site wide configuration

title: Zanui Engineering
locale: en_AU
description: Development and design blog from Zanui
logo: site-logo.png
search: true
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Zanui.com.au
  avatar: bio-photo.jpg
  email: engineering@zanui.com.au
  disqus-shortname:
  twitter: zanui
  facebook: zanui.com.au
  github: zanui
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: zanui
  instagram: zanui
  flickr: #username
  tumblr: #username
  google:
    plus: ZanuiAu
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
